### ISSUE TITLE
Do not use @11ty/eleventy 2.0.0-canary.18 and above for a while

### ISSUE THREAD

**Issue by kentaroi** [kentaroi/eleventy-sass#18]
Eleventy 2.0.0-canary.x had been stable for months.
However, there was a breaking change in the watcher in 2.0.0-canary.18, and Eleventy is being updated frequently since 2.0.0-canary.19 these days.

As a result, current eleventy-sass is not compatible with Eleventy 2.0.0-canary.18 and above.

Please use Eleventy 1.0.x or 2.0.0-canary.17 or below for a while.

**Comment by televators** [comment]
Thank you for alerting us all! Am just getting into 11ty and was tempted to try the new dev server setup. Will hold off since your plugin is more important to me than a new dev server.

Wasn't sure where to leave this so I guess here is it but thank you thank you thank you for writing such thorough, clear, and concise docs that don't try to teach coding 101 while explaining the details of an API. It drives me absolutely up the wall when docs are trying to be Codecademy and actual docs at the same time and succeed at neither. Yours has exactly the information and details I wanted at every step and you covered all the conceivable tweaks as far as a fresh user is concerned.

**Comment by kentaroi** [comment]
Thank you very, very much, @televators! I'm glad you liked it and really appreciate you taking the time to leave feedback.

**Comment by kentaroi** [comment]
I released eleventy-sass 2.1.6 that should fix all of the issues with Eleventy 2.0.0-canary.18 and above.
Thanks for your patience.
