### ISSUE TITLE
Possible conflict with eleventyComputed

### ISSUE THREAD

**Issue by redmagic** [kentaroi/eleventy-sass#29]
Hi,

This might be related to https://github.com/kentaroi/eleventy-sass/issues/13, but the other way around:

A page template has a `11tydata.js` file next to it which contains eleventyComputed functions.
These functions are called while processing the page template.

Now, a `.scss` file is placed next to the page template.

The functions inside eleventyComputed are called an extra time while processing the scss file.

These functions are called without page context, which might cause them to break.

The expected behavior is that the 11ty data file is not called/process for scss files.

If required, I could make a small reproduction repo, but I hope this description is enough to identify the issue.

Thanks in advance for looking into this!

**Comment by kentaroi** [comment]
Thanks for filing the issue.
However, I am wondering if it should be fixed in the plugin.

The behavior of Eleventy you described seems to be the spec of Eleventy.
A `11tydata.js` file will be applied to every template file in the directory.
In this sense, you should implement functions inside `eleventyComputed` not to break even if a template file does not have any front matter data like `.scss` file, or you should not put any files that do not have front matter data in the directory.

**Comment by redmagic** [comment]
Hi, thanks for your quick reply.

Yes, I agree it is a bit unclear where this issue comes from. Removing the plugin solves the problem, so it seemes somehow related.

However, your remark about data files triggered me, depending on the name it is applied on all files in the directory or on a specific template file. One of our templates had the same name as the directory itself, so we could fix this by making the data file more specific.

**Comment by kentaroi** [comment]
Hi, @redmagic!

If you remove the plugin from your project, `.scss` files are no longer templates of Eleventy and the problem will disappear.
Therefore, you cannot say it is "somehow related" by "Removing the plugin solves the problem."

But, I understand the inconvenience.
