### ISSUE TITLE
Sass version management

### ISSUE THREAD

**Issue by xplosionmind** [kentaroi/eleventy-sass#32]
Hi! Sorry if my question is a bit naive/off-topic, but I am trying to learn, and I don’t really know where/who to ask this.

I have eleventy-sass version 2.2.4, and in its `package.json` the minimum `sass` dependency is set by `"^1.49.7"`. If I go into the `sass`’s `package.json`, I see that its version is 1.71.1. The latest Sass version is 1.77.5, though. Even if I run `pnpm up sass`, the version does not change.

Could you help me understand how to upgrade Sass, and what determines the version number being used?

Thanks a lot!

**Comment by kentaroi** [comment]
Thank you for your question, @xplosionmind!

Since I'm not a `pnpm` user, I'm not sure how to address it.
I can only say that `"^1.49.7"` means 1.49.7 <= package version < 2.0.0 and I would run `npm update sass` when using `npm` to update `sass` version to the latest (1.77.5).

If `pnpm` won't update `sass` to the latest, there should be another package that is preventing it. If I were you, I would ask the way to address it in a `pnpm` community, or I would install `sass` 1.77.5 to see the error message, or forcibly install it to see how the dependencies get broken.

**Comment by xplosionmind** [comment]
Thanks for your reply, @kentaroi! Apparently, even if it was in node_modules, sass was not in `package.json`. It was sufficient to run `pnpm i sass`
