### ISSUE TITLE
Fails to rebuild on change to dependencies if using incremental builds

### ISSUE THREAD

**Issue by mathew-c** [kentaroi/eleventy-sass#4]
`npx @11ty/eleventy --serve` is working fine for me, including with use/forward SCSS file dependencies. However, `npx @11ty/eleventy --serve --incremental`, fails to rebuild on changes to SCSS file dependencies. Is this expected behavior?

After `DEBUG=*EleventySass* npx @11ty/eleventy --serve --incremental`, I'm seeing an initial successful compile and write:

      Dev:EleventySass getCacheKey(contents, ./src/assets/styles/main.scss) -> src/assets/styles/main.scss2022-04-21T18:40:26.878Zinitial +0ms
      Dev:EleventySass Has compiled ./src/assets/styles/main.scss +243ms
      ...
      [11ty] Copied 1 file / Wrote 4 files in 0.38 seconds (v1.0.0)
      [11ty] Watching…

If I change a line in a dependent SCSS file and save, I'm seeing (in part):

      [11ty] File changed: src/assets/styles/3-elements/_page.scss
      Dev:EleventySass eleventy.beforeWatch queue: [ './src/assets/styles/3-elements/_page.scss' ] +2m
      Dev:EleventySass getCacheKey(contents, ./src/assets/styles/main.scss) -> src/assets/styles/main.scss2022-04-21T18:41:57.455Z +34ms
      Dev:EleventySass Has compiled ./src/assets/styles/main.scss +111ms 
      ...
      Dev:EleventySass getCacheKey(contents, ./src/assets/styles/3-elements/_page.scss) -> src/assets/styles/3-elements/_page.scss2022-04-21T18:41:57.455Z +0ms
      ...
      Dev:EleventySass Actually, didn't compile ./src/assets/styles/3-elements/_page.scss, because the filename starts with "_" +0ms
      [11ty] Wrote 0 files (skipped 4) in 0.17 seconds (v1.0.0)
      EleventySass:SourceMapStore dist/assets/styles/main.css.map written.. +2m
      [Browsersync] Reloading Browsers...

The result is that `main.css.map` is compiled and written out with the changes, but `main.css` is not.

Relevant lines from `.eleventy.js`:

      eleventyConfig.addPlugin(eleventySass, {
        sass: {
          loadPaths: ["src/assets/styles/"],
        }
      });

**Comment by kentaroi** [comment]
Thank you very much for letting me know.
Of course, it is not expected behaviour.
I'm ashamed that I didn't pay attention to the incremental builds feature when creating this plugin.
If I may ｍake an excuse, the documentation for the incremental builds feature for custom template extensions has not yet been written (https://www.11ty.dev/docs/languages/custom/#isincrementalmatch).

Anyway, I'll investigate it.

**Comment by mathew-c** [comment]
Ty, I wasn't meaning to be sarcastic re: the intended feature comment, just typing too fast. Appreciate you taking a look at it and the all the work you've done on this already.

**Comment by kentaroi** [comment]
Thanks for your warm words 😄 
I've just published version 1.2.0.
Hope this works.

**Comment by kentaroi** [comment]
> Ty, I wasn't meaning to be sarcastic re: the intended feature comment, just typing too fast.

As you may have already noticed, I am not good at English. I am not enough skilled in English to read or write English sentences sarcastically. So, don't worry about it. I'm just grateful to you for creating the issue, because the fact is I ignored the incremental builds when creating the plugin and you reminded me of that.

To support the incremental builds, I just read part of the Eleventy code and I don't grasp the whole process of the incremental builds, but the v1.2.0 seems to work with the `--incremental` option in my local environment.
So, I hope you will give it a try.

**Comment by mathew-c** [comment]
Works perfect for me. Thank you so much!

**Comment by kentaroi** [comment]
Glad it worked out. Thank you for confirming!
